name: Build & Release

on:
  push:
    tags: [ '*' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: GH Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: "./build/libs/MoreFoWorld*.jar"
        generate_release_notes: true
        draft: false
        prerelease: false
