name: Build & Release

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Read version
        id: version
        run: |
          echo "::set-output name=version::$(cat version | head -n 1)"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build

      - name: Release
        uses: HSGamer/action-mcreleaser@main
        with:
          files: build/libs/MoreFoWorld-*-all.jar
        env:
          DESCRIPTION: ${{ steps.changelog.outputs.changelog }}
          GAME_VERSIONS: ${{ steps.version.outputs.version }}

          GITHUB_TOKEN: ${{ github.token }}

          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_PROJECT: saPdoNQI
          MODRINTH_LOADERS: folia

          HANGAR_KEY: ${{ secrets.HANGAR_KEY }}
          HANGAR_PROJECT: MoreFoWorld
          HANGAR_PLATFORM: paper